application: hangulize
version: 0-1-dev
runtime: python
threadsafe: false
api_version: 1

libraries:
- name: babel
- name: pytz
- name: flask
- name: flask-babel
- name: hangulize
- name: markdown

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /crossdomain.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml

- url: /static
  static_dir: static

- url: /docs/(.+)
  static_files: docs/\1
  upload: docs/(.+)

- url: /docs/
  static_files: docs/index.html
  upload: docs/index.html

- url: /.*
  script: main.py
