runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /crossdomain.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml

- url: /static
  static_dir: static

- url: /docs/(.+)
  static_files: docs/\1
  upload: docs/(.+)

- url: /docs/
  static_files: docs/index.html
  upload: docs/index.html

- url: /.*
  script: hangulizeweb.app

automatic_scaling:
  max_instances: 1
  min_instances: 1
  max_idle_instances: 1
  min_idle_instances: 1

inbound_services:
- warmup
